### ISSUE TITLE
Anagram API

### ISSUE THREAD

**Issue by SysVoid** [lyndseybrowning/wordapi.net#2]
# Generate
It would be nice if you could make an API to generate a list of anagrams with a `?length=x` or just a random length. Results would be returned as JSON `["liek", "tihs"]`.

## Examples
```
[GET] https://wordapi.net/anagrams/generate/length/5
```
```
[
    "slaet",
    "plaet",
    "creta",
    "..."
]
```

```
[GET] https://wordapi.net/anagrams/generate/word/car/2
```
```
[
    "rac",
    "rca"
]
```

# Solve
It'd also be nice if the API could take a list of anagrams as POST (with the anagrams as a JSON array in the same format as **Generate**). It would then return the words in this format:

```
[POST] https://wordapi.net/anagrams/solve
```
Request body:
```
["rca", "rac", "vile", "evil"]
```

Request response:
```
{
    "rca": ["car"],
    "rac": ["car"],
    "vile": ["evil", "live", "veil", "vile"],
    "evil": ["evil", "live", "veil", "vile"]
}
```
    

And so on.

**Comment by lyndseybrowning** [comment]
This suggestion has now been implemented in route.anagrams.js.
